console.log(`April 1th Reorganizacion `);
console.log(`April 2th Two it's was a good day with the studen in MT`);
console.log(`April 3th first _DataBase class with 11º`);
console.log(`April 4th a good effort `);
console.log(`April 5th 💀 today was a wasted day in partre`);
console.log(`April 6th `);
console.log(`April 7th Iam creating a road and example for my first Lab Class`);
console.log(`April 8th I STARED THE LAB WITH THE GUYS`);
console.log(`April 9th It was a simple day and i rowked un the pc room`);
console.log(`April 10th Wonderfull satabase class with the MT 11º `);
console.log(`April 11th we save the oportunity the change day to day`);
console.log(`April 12th I consfiused abou take the sound`);
console.log(`April 13th i didnt feel confitbale, cus  the thesicion was in my head`);
console.log(`April 14th it was an interesting day, trying to reorganize my routine.s `);
console.log(`April 15th booring day in anormal journary in the collage `);
console.log(`April 16th it was a good day, I was very strict with my students `);
console.log(`April 17th it was a grate day with my students practice SQL for the first time  `);
console.log(`April 18th   `);
console.log(`April 19th  I felt a good ambiance at school. `);

