console.log(`April 1th   Reorganizacion `);
console.log(`April 2th   Two it's was a good day with the studen in MT`);
console.log(`April 3th   first _DataBase class with 11º`);
console.log(`April 4th   a good effort `);
console.log(`April 5th   💀 today was a wasted day in partre`);
console.log(`April 6th   💀 forget the day`);
console.log(`April 7th   Iam creating a road and example for my first Lab Class`);
console.log(`April 8th   I STARED THE LAB WITH THE GUYS`);
console.log(`April 9th   It was a simple day and i rowked un the pc room`);
console.log(`April 10th  Wonderfull satabase class with the MT 11º `);
console.log(`April 11th  we save the oportunity the change day to day`);
console.log(`April 12th  I consfiused abou take the sound`);
console.log(`April 13th  i didnt feel confitbale, cus  the thesicion was in my head`);
console.log(`April 14th  it was an interesting day, trying to reorganize my routine.s `);
console.log(`April 15th  booring day in anormal journary in the collage `);
console.log(`April 16th  it was a good day, I was very strict with my students `);
console.log(`April 17th  it was a grate day with my students practice SQL for the first time  `);
console.log(`April 18th  I was working inn the journary `);
console.log(`April 19th  I felt a good ambiance at school. `);
console.log(`April 20th  I Lost the day`);
console.log(`April 21th  this Sunday was a restart `);
console.log(`April 22th  Today was the firts Lab Class, and was intersting`);
console.log(`April 23th  The first time all MT 10th graders come to class`);
console.log(`April 24th  Speach for MT10`);
console.log(`April 25th  today I was at home doing school homework and did not concentrate on studying well. `);
console.log(`April 26th  probelma with the schedule, problem with the computer rooms `);
console.log(`April 27th  💀 `);
console.log(`April 28th  STAR THE REST OF MY BIG CHANCE`);
console.log(`April 29th  Today  i showed my lab students all my  `);
console.log(`April 30th  Good class with my  MT 10º studens , with the pet visist  `);
console.log(`April 1th   today was a holiday and I was working on organizing some things for the study plan. `);
console.log(`April 2th   Thurdayyy... basci day , but in the end on the day i was workin in the medellin digital `);
console.log(`April 3th   friday, simple day `);
console.log(`April 4th   saturday, i was watching PG, but before i study DOM manipulation `);
console.log(`April 5th   Wear day , but iam ready to start my change `);
console.log(`April 6th   In the lab today practice array method and a bit DOM`);
console.log(`April 7th   i talked seriusly with the MT 10º, bu a feel wear`);
console.log(`April 8th   it was a good day, champions day, but we worked in BD suceccfully`);
console.log(`April 9th   `);
console.log(`April 10th   talk eith the rector aboyut Programin festival and star my vacation`);
console.log(`April 11th   simple day a watch PG`);
console.log(`April 12th   finished PG`);
console.log(`April 13th   holly day and did nothing special`);
console.log(`April 14th   otganize my routine a practice a little bit`);
console.log(`April 15th   teachers day. i bought some thin for the house, and practice My SQL`);
console.log(`April 16th   i talked with myself and feel good `);
console.log(`April 17th   just 3 pull in the bar 😭`);
console.log(`April 18th   Good day win UI and Valeris Project 😭`);
console.log(`April 19th   Hard Programing Practice`);
console.log(`April 21th   🌧 crazy inn the mornig. now i gonna practice recat. FAILED `);
console.log(`April 22th   Wera day , MT 11º no fue completo y raro `);
console.log(`April 22th   Wera day , MT 11º no fue completo y raro `);


