console.log(`Jun 01th Drinking`)
console.log(`Jun 02th Drinking`)
console.log(`Jun 03th Final Day`)
console.log(`Jun 04th Meeting the posible disaster coor`)
console.log(`Jun 05th APPOINTMENT WITH JULIO CESAR`)
console.log(`Jun 06th stay at home.. and tried to go to f*ck to Jim`)
console.log(`Jun 07th Star Firt JAVA line :)`)
console.log(`Jun 08th Try to organize idea and method to continue`)
console.log(`Jun 09th unpleasant moment with This son of a B`)
console.log(`Jun 10th Legendary Picture with my 11 guys`)
console.log(`Jun 11th go out with lore `)
console.log(`Jun 12th go out with the son of a B`)
console.log(`Jun 13th Rest day`)
console.log(`Jun 14th `)
console.log(`Jun 15th `)
