console.log(`Jun 01th Drinking`)
console.log(`Jun 02th Drinking`)
console.log(`Jun 03th Final Day`)
console.log(`Jun 04th Meeting the posible disaster coor`)
console.log(`Jun 05th APPOINTMENT WITH JULIO CESAR`)
console.log(`Jun 06th APPOINTMENT WITH JULIO CESAR`)
console.log(`Jun 07th APPOINTMENT WITH JULIO CESAR`)
console.log(`Jun 08th APPOINTMENT WITH JULIO CESAR`)
