console.log(`Jun 01th Drinking`)
console.log(`Jun 02th Drinking`)
console.log(`Jun 03th Final Day`)
console.log(`Jun 04th Meeting the posible disaster coor`)
console.log(`Jun 05th APPOINTMENT WITH JULIO CESAR`)
console.log(`Jun 06th stay at home.. and tried to go to f*ck to Jim`)
console.log(`Jun 07th Star Firt JAVA line :)`)
console.log(`Jun 08th Try to organize idea and method to continue`)
console.log(`Jun 09th unpleasant moment with This son of a B`)
console.log(`Jun 10th Legendary Picture with my 11 guys`)
console.log(`Jun 11th go out with lore `)
console.log(`Jun 12th go out with the son of a B`)
console.log(`Jun 13th Rest day`)
console.log(`Jun 14th Havert moon Digimosn a Sterdsw ville`)
console.log(`Jun 15th Excepional mornig `)
console.log(`Jun 16th ♥ love`)
console.log(`Jun 17th Watching  Again DR HOUSE`)
console.log(`Jun 18th ♥ Final Staredew ville play`)
console.log(`Jun 19th Organize the house`)
console.log(`Jun 20th I'm lost, ...`)
console.log(`Jun 21th is The last Dance ?`)
console.log(`Jun 22th 🥂🍹`)
console.log(`Jun 23th Back Home`)
console.log(`Jun 24th Stared ville`)
console.log(`Jun 25th Grate Phone call with wal  and poa`)
console.log(`Jun 26th Great Phone call with Law`)
console.log(`Jun 27th Figthing with claro`)
console.log(`Jun 28th Drink ans spend a lot of money `)
console.log(`Jun 29th Drinkung in Dey's house`)
console.log(`Jun 30th STOP`)
console.log(`Jul 01th Sendind pending `)
console.log(`Jul 02th My BirthDay`)
console.log(`Jul 03th Its all star`)
console.log(`Jul 04th Procesing...`)
console.log(`Jul 05th I Gonna make today happen`)
console.log(`Jul 06th trying`)
console.log(`Jul 07th Sick`)
console.log(`Jul 08th Apply for a job offer`)
console.log(`Jul 09th Sick`)
console.log(`Jul 10th advance to the interview stage`)
console.log(`Jul 11th Great interview`)
console.log(`Jul 12th creating my video class F J`)
console.log(`Jul 13th THAT PAIN`)
console.log(`Jul 14th 15 DAY 😂😀`)
console.log(`Jul 15th THE SECOUND `)
console.log(`Jul 16th Rstingg...`)
console.log(`Jul 17th get de oparation day`)
console.log(`Jul 18th Lokking for maestrias `)
console.log(`Jul 19th Lose`)
console.log(`Jul 20th Nothing...`)
console.log(`Jul 21th My operation 👁`)
console.log(`Jul 21th TDEA`)
console.log(`Jul 22th Cita`)   
console.log(`Jul 23th Stay at home`)   
console.log(`Jul 24th General Aful exam `)   
console.log(`Jul 25th Another ?`)   
console.log(`Jul 26th Talento Tech`)   
console.log(`Jul 27th stared with all`)   
console.log(`Jul 28th We tried and fail`)   
console.log(`Jul 29th TdeA in trouble`)   
console.log(`Jul 30th Talento teach`)   
console.log(`Jul 31th its NOW`)   
console.log(`Ago 01th Please`)   
console.log(`Ago 02th BIG TIME`)   
console.log(`Ago 03th Thinking about BIG descition`)   
console.log(`Ago 04th Cordal Extarer finished`)   
console.log(`Ago 05th Last deatil`)   
console.log(`Ago 06th Stared`)   
console.log(`Ago 07th BY 0`)   
console.log(`Ago 08th Retaking`)   
console.log(`Ago 09th A lot of practice`)   
console.log(`Ago 10th Practice`)   
console.log(`Ago 11th extra puntos`)   
console.log(`Ago 12th Rertake 11 MT`)   
console.log(`Ago 13th Rertake 10 MT`)   
console.log(`Ago 14th Little figth`)   
console.log(`Ago 15th Travelin to CQT`)   
console.log(`Ago 16th ALANA Moment`)   
console.log(`Ago 17th Back to medallo and Java`)   
console.log(`Ago 18th Rest day`)   
console.log(`Ago 19th SQL Practice`)   
console.log(`Ago 20th Final Arrays Class`)   
console.log(`Ago 21th Array Examen a reuniopn with UB Teach`)   
console.log(`Ago 22th i didnt go to collage`)   
console.log(`Ago 23th REACT COME BACK`)   
console.log(`Ago 24th prgramin, gym clean , good all`)   
console.log(`Ago 25th Project 2 React`)   
console.log(`Ago 26th Lose 11 class for not avis`)   
console.log(`Ago 27th Big POO Class with 10`)   
console.log(`Ago 28th Back to the GYM`)   
console.log(`Ago 28th Back to the GYM`)   
console.log(`Ago 28th Back to the GYM`)   
console.log(`Ago 28th Back to the GYM`)   
console.log(`Sep 01th New SENA Teach`)   
console.log(`Ago 02th Fake Final Examen`)   