console.log(`Jan 01th NEW YEAR`)    
console.log(`Jan 02th Father mment`)    
console.log(`Jan 03th Talking with the boss`)    
console.log(`Jan 04th Light Off`)    
console.log(`Jan 05th Arrived to Mes`)    
console.log(`Jan 06th Arranca o no Arranca`)    
console.log(`Jan 07th GPT Explai like a master`)    
console.log(`Jan 08th Organize`)    
console.log(`Jan 08th Internet is home`)    
console.log(`Jan 10th Gina `)    
console.log(`Jan 11th Ready or not `)    
console.log(`Jan 12th Cant haen again`)    
console.log(`Jan 13th Talk with Plumaman and close decisione`)    
console.log(`Jan 14th Back to the project`)    
console.log(`Jan 15th Reunion with frend rector to talk`)    
console.log(`Jan 16th Project reunion`)    
console.log(`Jan 17th Working in the Saas`)    
console.log(`Jan 18th Blueblos 1 cap and Working in the Saas`)    
console.log(`Jan 19th Final Day`)    
console.log(`Jan 20th The decision`)    
console.log(`Jan 21th 1 chance`)    
console.log(`Jan 22th Final chance`)    
console.log(`Jan 23th I cant`)
console.log(`Feb 01th THE FINAL DAY `)
console.log(`Feb 02th `)    
console.log(`Feb 03th FIRST DAY BACK TO THE SCHOOL`)    
console.log(`Feb 04th Final idea software`)    
console.log(`Feb 05th Firt Meet with MT`)    
console.log(`Feb 06th close to finish the Project`)    
console.log(`Feb 07th `)    
console.log(`Feb 08th Working in NH - Project`)    
console.log(`Feb 09th Firts Mt Maqietation calss`)    
console.log(`Feb 10th First class with 10°`)    
console.log(`Feb 11th Beatriz bitch `)    
console.log(`Feb 12th SaaS ? `)    
console.log(`Feb 13th Saas SOccer `)    
console.log(`Feb 14th `)    
console.log(`Feb 15th `)    
console.log(`Feb 16th APto o que `)    
console.log(`Feb 17th APto o que `)    
console.log(`Feb 18th `)    
console.log(`Feb 19th `)    
console.log(`Feb 20th `)    
console.log(`Feb 21th `)    
console.log(`Feb 22th  Reset my maind`)    
console.log(`Feb 22th  Melany idin my`)    
console.log(`Feb 22th  Melany idin my`)    
console.log(`Mar 01th `)    
console.log(`Mar 02th `)    
console.log(`Mar 03th `)    
console.log(`Mar 04th `)    
console.log(`Mar 05th `)    
console.log(`Mar 06th `)    
console.log(`Mar 07th `)    
console.log(`Mar 08th `)    
console.log(`Mar 09th `)    
console.log(`Mar 10th `)    
console.log(`Mar 11th `)    
console.log(`Mar 12th `)    
console.log(`Mar 13th `)    
console.log(`Mar 14th `)    
console.log(`Mar 15th `)    
console.log(`Mar 16th `)    
console.log(`Mar 17th `)    
console.log(`Mar 18th `)    
console.log(`Mar 19th `)    
console.log(`Mar 20th `)    
console.log(`Mar 21th `)    
console.log(`Mar 22th `)    
console.log(`Mar 23th `)    
console.log(`Mar 24th `)    
console.log(`Mar 25th `)    
console.log(`Mar 26th `)    
console.log(`Mar 27th `)    
console.log(`Mar 28th `)    
console.log(`Mar 29th `)    
console.log(`Mar 30th `)    
console.log(`Mar 31th `)    
console.log(`Apr 01th `)    
console.log(`Apr 02th `)    
console.log(`Apr 03th `)    
console.log(`Apr 04th `)    
console.log(`Apr 05th `)    
console.log(`Apr 06th `)    
console.log(`Apr 07th `)    
console.log(`Apr 08th `)    
console.log(`Apr 09th `)    
console.log(`Apr 10th `)    
console.log(`Apr 11th `)    
console.log(`Apr 12th `)    
console.log(`Apr 13th `)    
console.log(`Apr 14th `)    
console.log(`Apr 15th `)    
console.log(`Apr 16th `)    
console.log(`Apr 17th `)    
console.log(`Apr 18th `)    
console.log(`Apr 19th `)    
console.log(`Apr 20th `)    
console.log(`Apr 21th `)    
console.log(`Apr 22th `)    
console.log(`Apr 23th `)    
console.log(`Apr 24th `)    
console.log(`Apr 25th `)    
console.log(`Apr 26th `)    
console.log(`Apr 27th `)    
console.log(`Apr 28th `)    
console.log(`Apr 29th `)    
console.log(`Apr 30th `)    
console.log(`May 01th `)    
console.log(`May 02th `)    
console.log(`May 03th `)    
console.log(`May 04th `)    
console.log(`May 05th `)    
console.log(`May 06th `)    
console.log(`May 07th `)    
console.log(`May 08th `)    
console.log(`May 09th `)    
console.log(`May 10th `)    
console.log(`May 11th `)    
console.log(`May 12th `)    
console.log(`May 13th `)    
console.log(`May 14th `)    
console.log(`May 15th `)    
console.log(`May 16th `)    
console.log(`May 17th `)    
console.log(`May 18th `)    
console.log(`May 19th `)    
console.log(`May 20th `)    
console.log(`May 21th `)    
console.log(`May 22th `)    
console.log(`May 23th `)    
console.log(`May 24th `)    
console.log(`May 25th `)    
console.log(`May 26th `)    
console.log(`May 27th `)    
console.log(`May 28th `)    
console.log(`May 29th `)    
console.log(`May 30th `)    
console.log(`May 31th `)
console.log(`Jun 01th `)    
console.log(`Jun 02th `)    
console.log(`Jun 03th `)    
console.log(`Jun 04th `)    
console.log(`Jun 05th `)    
console.log(`Jun 06th `)    
console.log(`Jun 07th `)    
console.log(`Jun 08th `)    
console.log(`Jun 09th `)    
console.log(`Jun 10th `)    
console.log(`Jun 11th `)    
console.log(`Jun 12th `)    
console.log(`Jun 13th `)    
console.log(`Jun 14th `)    
console.log(`Jun 15th `)    
console.log(`Jun 16th `)    
console.log(`Jun 17th `)    
console.log(`Jun 18th `)    
console.log(`Jun 19th `)    
console.log(`Jun 20th `)    
console.log(`Jun 21th `)    
console.log(`Jun 22th `)    
console.log(`Jun 22th `)    


