console.log(`Jun 01th NEW YEAR`)    
console.log(`Jun 02th Father mment`)    
console.log(`Jun 03th Talking with the boss`)    
console.log(`Jun 04th Light Off`)    
console.log(`Jun 05th Arrived to Mes`)    
console.log(`Jun 06th Arranca o no Arranca`)    
console.log(`Jun 07th GPT Explai like a master`)    
console.log(`Jun 08th Organize`)    
console.log(`Jun 08th Internet is home`)    
console.log(`Jun 10th Gina `)    
console.log(`Jun 11th Ready or not `)    
console.log(`Jun 11th Cant haen again`)    
console.log(`Jun 11th Cant haen again`)    
    
