console.log(`Jun 01th NEW YEAR`)    
console.log(`Jun 02th Father mment`)    
console.log(`Jun 03th Talking with the boss`)    
console.log(`Jun 04th Light Off`)    
console.log(`Jun 05th Arrived to Mes`)    
console.log(`Jun 06th Arranca o no Arranca`)    
console.log(`Jun 07th GPT Explai like a master`)    
console.log(`Jun 08th Organize`)    
console.log(`Jun 08th Internet is home`)    
console.log(`Jun 10th Gina `)    
console.log(`Jun 11th Ready or not `)    
console.log(`Jun 12th Cant haen again`)    
console.log(`Jun 13th Talk with Plumaman and close decisione`)    
console.log(`Jun 14th Back to the project`)    
console.log(`Jun 15th Reunion with frend rector to talk`)    
console.log(`Jun 16th Project reunion`)    
console.log(`Jun 17th Working in the Saas`)    
console.log(`Jun 18th Blueblos 1 cap and Working in the Saas`)    
console.log(`Jun 19th Final Day`)    
console.log(`Jun 20th The decision`)    
console.log(`Jun 21th 1 chance`)    
console.log(`Jun 22th Final chance`)    
console.log(`Jun 23th I cant`)    
console.log(`Jun 24th Realize the sutuation`)    
console.log(`Jun 25th Deplyman `)    
console.log(`Jun 26th Deplyman`)    
console.log(`Jun 27th Deplyman`)    
console.log(`Jun 28th Deplyman`)    
console.log(`Jun 29th Deplyman final talk with law`)    
console.log(`Jun 30th `)    
console.log(`Jun 31th The say Before`)    
console.log(`Feb 01th THE FINAL DAY `)    
console.log(`Feb 02th `)    
console.log(`Feb 03th FIRST DAY BACK TO THE SCHOOL`)    
console.log(`Feb 04th Final idea software`)    
    
